config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :users

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
class ImageUploader < Shrine
  Attacher.validate do
    validate_max_size 5.megabyte, message: 'is too large (max is 5 MB)'
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png']
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  include ImageUploader[:image]

  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  
  validates :first_name, :last_name, presence: true
  validates :phone_number, uniqueness: true

  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
      redirect_back fallback_location: root_path
      flash[:alert] = 'Недостаточно прав для данного действия!'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.includes(:user).order(created_at: :desc).page params[:page]
  end

  def show; end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Ваш пост опубликован!'
      redirect_to post_path(@post)
    else
      flash.now[:alert] = 'Ваш новый пост не создан! Пожалуйста, проверьте форму.'
      render :new
    end
  end

  def edit
    authorize @post
  end

  def update
    authorize @post

    if @post.update(post_params)
      flash[:success] = 'Пост обновлен.'
      redirect_to post_path(@post)
    else
      flash.now[:alert] = 'Ошибка обновления. Пожалуйста, проверьте форму.'
      render :edit
    end
  end

  def destroy
    authorize @post
    
    if @post.destroy
      flash[:success] = 'Пост удален.'
    else
      flash.now[:alert] = 'Ошибка удаления. Пожалуйста, попробуйте еще раз.'
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

  <% if Rails.env.development? %>
    <% console %>
  <% end %>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:class => 'form'} do |f|%>
  <%= f.file_field :image %>
  <%= f.text_field :user_id %>
  <%= f.text_area :description, placeholder: "Придумайте подпись...", rows: "10"%>
  <%= f.submit 'Поделиться' %>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <td><%= image_tag post.image_url %></td>
  <td><%= link_to post.user.email, user_path(post.user) %></td>
  <td><%= post.description %></td>
  <td><%= link_to "Post № #{post.id}", post_path(post) %></td>
  <% if policy(post).edit? %>
    <td><%= link_to "Edit", edit_post_path(post)%></td>
  <% end %>
  <% if policy(post).destroy? %>
    <td><%= link_to "Delete", post_path(post), data: { method: :delete, confirm: 'Вы уверены, что хотите удалить пост?' } %></td>
  <% end %>
</tr>

app/views/posts/edit.html.erb
<main class="container">
  <%= render "form", post: @post %>
</main>

app/views/posts/index.html.erb
<main style="padding:25px;">
  <section class="posts index">
    <%= link_to "Create new post", new_post_path, style: "font-size:24px; padding: 1rem; color: black; border:1px solid red;" %>
    <table class="styled-table">
      <thead>
          <tr>
            <th>Image</th>
            <th>User</th>
            <th>Post Description</th>
            <th>Link to post</th>
            <th>Edit Post</th>
            <th>Delete Post</th>
          </tr>
      </thead>

      <tbody>
        <%= render @posts %>
      </tbody>
    </table>

    <% if @posts.total_pages > 1 %>
      <%= paginate @posts %>
    <% end %>
  </section>
</main>

app/views/posts/new.html.erb
<main class="container">
  <%= render "form", post: @post %>
</main>

app/views/posts/show.html.erb
<main class="form">
  <%= image_tag @post.image_url %>
  <%= link_to @post.user.email, user_path(@post.user) %>
  <%= @post.description %>
  <%= link_to "Back to main", root_path %>
</main>

<%= debug @post %>